version: "3.7"
services:
  prometheus:
    image: prom/prometheus
    container_name: stats_spike_prometheus
    ports:
      - "9090:9090"
    volumes:
      - /Users/magnusblondal/code/vis_sandbox/stats_spike/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor
  
  cadvisor:
    image: google/cadvisor:v0.29.0
    restart: always
    ports:
        - "8080:8080"
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
        - "3000:3000"
    
    volumes:
        - /Users/magnusblondal/code/vis_sandbox/stats_spike/grafana:/var/lib/grafana
    environment:
        - HTTP_USER=admin
        - HTTP_PASS=admin
    depends_on:
        - prometheus

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: stats_spike_nginx_proxy
    ports:
        - "80:80" 
        - "443:443"
    volumes: 
        - /Users/magnusblondal/code/vis_sandbox/stats_spike/https_certs:/etc/nginx/certs:ro
        - nginx-vol:/etc/nginx/vhost.d
        - nginx-vol:/usr/share/nginx/html
        - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: stats_spike_nginx_letsencrypt
    volumes: 
        - /Users/magnusblondal/code/vis_sandbox/stats_spike/https_certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - nginx-vol:/etc/nginx/vhost.d
        - nginx-vol:/usr/share/nginx/html
    environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
        - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
        - "9092:9092"
    environment:
        KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_CREATE_TOPICS: "authorization:1:1"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:                                                                                                                                                                                                
        - /var/run/docker.sock:/var/run/docker.sock

  apinn:
    image: apinn:latest
    container_name: stats_spike_apinn
    restart: always
    expose:
      - "80"
    ports:
      - "5000:80"
    environment:
      - VIRTUAL_HOST=vit.hux.is
      - LETSENCRYPT_HOST=myrazorapp.glenmccallum.com
      - LETSENCRYPT_EMAIL=glen.mccallum@protonmail.com
    
  maurinn:
    image: maur:latest
    container_name: stats_spike_maurinn
    restart: always

volumes:
  nginx-vol:
        
