global:
    scrape_interval: 10s
    scrape_timeout: 10s
    evaluation_interval: 1m

scrape_configs:
    - job_name: 'node'
      static_configs:
        - targets:
          - localhost:9100

    - job_name: 'cadvisor'
      static_configs:
        - targets: ['docker.for.mac.localhost:8080']

    - job_name: 'apinn'
      static_configs:
        - targets: ['docker.for.mac.localhost:5000']
